### ISSUE TITLE
go-openai Api Proxy

### ISSUE THREAD

**Issue by zer0000001** [pkdindustries/soulshack#20]
it is also possible to use other apis, e.g. https://openrouter.ai. I found this in the documentation of go-openai.

config := openai.DefaultConfig("token")
proxyUrl, err := url.Parse("http://localhost:{port}")
if err != nil {
	panic(err)
}
transport := &http.Transport{
	Proxy: http.ProxyURL(proxyUrl),
}
config.HTTPClient = &http.Client{
	Transport: transport,
}

c := openai.NewClientWithConfig(config)

But I don't know how to put it here

**Comment by alexschlessinger** [comment]
hey, you are right this is something that should certainly be configurable.
